version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-auth
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - docker_fastfood-network

networks:
  docker_fastfood-network:
    external: true