name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

defaults:
  run:
    working-directory: ./function/FoodcoreAuth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Dependencies Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish Function
        run: dotnet publish --configuration Release --output ./publish

      - name: Zip package
        run: zip -r functionapp.zip ./publish
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-zip
          path: ./functionapp.zip