name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

defaults:
  run:
    working-directory: ./function/FoodcoreAuth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Setup Azure Functions Core Tools
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs 2>/dev/null)-prod $(lsb_release -cs 2>/dev/null) main" > /etc/apt/sources.list.d/dotnetdev.list'
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-4

      - name: Dependencies Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish Function
        run: dotnet publish --configuration Release --output ./publish

      - name: Zip package
        run: |
          cd publish
          zip -r ../functionapp.zip .
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-zip
          path: ./function/FoodcoreAuth/functionapp.zip
      
      - name: Create .env file for Function App
        run: |
          cat <<EOF > .env
          AWS_CREDENTIALS="[default]
          aws_access_key_id=EXAMPLE
          aws_secret_access_key=EXAMPLE
          aws_session_token=EXAMPLE"
          
          AWS_REGION=EXAMPLE
          
          COGNITO_USER_POOL_ID=EXAMPLE
          COGNITO_APP_CLIENT_ID=EXAMPLE
          
          DEFAULT_CUSTOMER_PASSWORD=EXAMPLE
          EOF 
      
      - name: Start Function App
        run: func start --port 7025 & leep 10
        
      - name: Download openapi.json
        run: curl -o openapi.json http://localhost:7025/api/openapi/v3.json

      - name: Upload openapi.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-json
          path: ./function/FoodcoreAuth/openapi.json